Attempting to open file inputs/two_images.fits
File opened successfully.
Running basic FITS verification with external call to ftverify.
Nothing from ftverify, trying with astropy.io.fits.verify(option='exception')
Found a file with an image in the PRIMARY extension.  Testing as an IMAGE.

=============== Checking 'PRIMARY' extension against 'IMAGE' standard ===============

WARNING3:  WCS.validate[key=' ']:  RADECSYS= 'FK5 ' / WCS for this file the RADECSYS keyword is deprecated, use RADESYSa.
WARNING3:  WCS.validate[key=' ']:  'datfix' made the change 'Invalid parameter value: inconsistent date '1991-03-20''.
WARNING3:  WCS.validate[key=' ']:  'celfix' made the change 'Unrecognized projection code (-TA in CTYPE2)'.
Checking keywords:


=============== Checking '' extension against 'IMAGE' standard ===============

Checking keywords:

ERROR: Key FILTER incorrect in two_images.fits[]
        Eval(h.Exists('FILTER'))==False
ERROR: Key HDUCLASS incorrect in two_images.fits[]
        Eval(h.hasVal('HDUCLASS','OGIP'))==False
ERROR: Key INSTRUME incorrect in two_images.fits[]
        Eval(h.Exists('INSTRUME'))==False
ERROR: Key TELESCOP incorrect in two_images.fits[]
        Eval(h.Exists('TELESCOP'))==False

=============== 4 Errors; 0 (level==2) warnings;  3 (level==3) warnings found in 2 extensions checked ===============


===========================================================

FAILURE: inputs/two_images.fits is not a Valid OGIP formatted file
Please see TBD: 
Available at
   TBD
